# Generated by Django 4.0 on 2021-12-15 07:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(3)])),
                ('refer_id', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.MaxLengthValidator(8)], verbose_name='Код реферальной ссылки')),
                ('name', models.CharField(max_length=80, verbose_name='Имя пользователя')),
                ('username', models.CharField(max_length=40, verbose_name='Логин пользователя')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='MessageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_body', models.TextField(verbose_name='Текст сообщения')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время получения')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bot.usermodel', verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
