# Generated by Django 4.0 on 2021-12-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_usermodel_refer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
